# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"

  config.ssh.forward_agent = "true"
  config.ssh.forward_x11 = "true"

  config.vm.provider :libvirt do |libvirt|
    #libvirt.disk_bus = "virtio"
    libvirt.management_network_name = "adm-lan"
    libvirt.management_network_address = "192.168.0.0/24"
    #libvirt.nic_model_type = "virtio"
    #libvirt.graphics_type = "vnc"
    #libvirt.graphics_autoport = "yes"
    #libvirt.graphics_port = "5901"
    #libvirt.keymap = "de-de"
    #libvirt.graphics_ip = "0.0.0.0"
    #libvirt.video_type = "qxl"
    #libvirt.video_vram = "65536"
    #libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
    #libvirt.host = "localhost"
    #libvirt.username = 'rrutkowski'
    libvirt.storage_pool_name = "default"
    libvirt.default_prefix = ""
    #libvirt.connect_via_ssh = true
  end

  config.vm.define :jenkins do |machine|
    machine.vm.hostname = "jenkins.adm.lan"

    machine.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.machine_virtual_size = 96
      domain.nested = true
      domain.cpu_model = 'host-model'
    end

    machine.vm.synced_folder("./vagrant", "/vagrant", type: 'rsync')
    machine.vm.network :public_network, :ip => "192.168.0.30", :dev => "virbr0", :mode => "bridge", :type => "bridge", :network_name => "adm-lan"
  end

  config.vm.provision "shell" do |command|
    command.path = "../shared/setup/common.sh"
    command.upload_path = "/tmp/common.sh"
  end

  phases=['bootstrap', 'postinstall']
  components=['mirror', 'jenkins', 'tools']

  phases.each do |phase|
    config.vm.provision "shell", path: "setup/#{phase}.sh"
    components.each do |component|
      config.vm.provision "shell" do |command|
        command.path = "../shared/setup/#{component}/#{phase}.sh"
        command.args = ["#{phase}", "#{component}"]
      end
    end
  end
end
