# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.ssh.forward_agent = "true"
  config.ssh.forward_x11 = "true"

  config.vm.provider :libvirt do |libvirt|
    #libvirt.disk_bus = "virtio"
    libvirt.management_network_name = "adm-lan"
    libvirt.management_network_address = "192.168.0.0/24"
    #libvirt.nic_model_type = "virtio"
    #libvirt.graphics_type = "vnc"
    #libvirt.graphics_autoport = "yes"
    #libvirt.graphics_port = "5901"
    #libvirt.keymap = "de-de"
    #libvirt.graphics_ip = "0.0.0.0"
    #libvirt.video_type = "qxl"
    #libvirt.video_vram = "65536"
    #libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
    #libvirt.host = "localhost"
    #libvirt.username = 'rrutkowski'
    libvirt.storage_pool_name = "default"
    libvirt.default_prefix = ""
    #libvirt.connect_via_ssh = true
  end

  phases=['bootstrap', 'postinstall']
  components=['mirror', 'libvirt', 'docker-ce', 'foreman', 'tools']

  config.vm.define "foreman-prd" do |machine|
    machine.vm.hostname = "foreman-prd.prd.lan"

    machine.vm.provider :libvirt do |domain|
      domain.memory = 16384
      domain.cpus = 8
      domain.machine_virtual_size = 128
      domain.nested = true
      domain.cpu_model = 'host-model'
    end
    machine.vm.synced_folder("./vagrant", "/vagrant", type: 'rsync')
    machine.vm.network :private_network, :ip => "192.168.10.10", :dev => "virbr1", :mode => "bridge", :type => "bridge", :network_name => "prd-lan"
  end

  config.vm.define "foreman-dev" do |machine|
    machine.vm.hostname = "foreman-dev.dev.lan"

    machine.vm.provider :libvirt do |domain|
      domain.memory = 16384
      domain.cpus = 8
      domain.machine_virtual_size = 128
      domain.nested = true
      domain.cpu_model = 'host-model'
    end
    machine.vm.synced_folder("./vagrant", "/vagrant", type: 'rsync')
    machine.vm.network :private_network, :ip => "192.168.20.10", :dev => "virbr2", :mode => "bridge", :type => "bridge", :network_name => "dev-lan"
  end

  config.vm.provision "shell" do |command|
    command.path = "../shared/setup/common.sh"
    command.upload_path = "/tmp/common.sh"
  end

  phases.each do |phase|
    config.vm.provision "shell" do |command|
      command.path = "setup/#{phase}.sh"
      command.args = ["#{phase}", "box"]
    end
    components.each do |component|
      config.vm.provision "shell" do |command|
        command.path = "../shared/setup/#{component}/#{phase}.sh"
        command.args = ["#{phase}", "#{component}"]
      end
    end
  end
end
