# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"

  config.ssh.forward_agent = "true"
  config.ssh.forward_x11 = "true"

  config.vm.provider :libvirt do |libvirt|
    #libvirt.disk_bus = "virtio"
    libvirt.management_network_name = "adm-lan"
    libvirt.management_network_address = "192.168.0.0/24"
    #libvirt.nic_model_type = "virtio"
    #libvirt.graphics_type = "vnc"
    #libvirt.graphics_autoport = "yes"
    #libvirt.graphics_port = "5901"
    #libvirt.keymap = "de-de"
    #libvirt.graphics_ip = "0.0.0.0"
    #libvirt.video_type = "qxl"
    #libvirt.video_vram = "65536"
    #libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
    #libvirt.host = "localhost"
    #libvirt.username = 'rrutkowski'
    libvirt.storage_pool_name = "default"
    libvirt.default_prefix = ""
    #libvirt.connect_via_ssh = true
  end

  config.vm.define :foreman_prd do |machine|
    machine.vm.hostname = "foreman-prd.prd.lan"

    machine.vm.provider :libvirt do |domain|
      domain.memory = 16384
      domain.cpus = 8
      domain.machine_virtual_size = 144
      domain.nested = true
      domain.cpu_model = 'host-model'
    end
    machine.vm.network :public_network, :ip => "172.16.10.10", :dev => "virbr1", :mode => "bridge", :type => "bridge", :network_name => "prd-lan"
  end

  config.vm.define :foreman_dev do |machine|
    machine.vm.hostname = "foreman-dev.dev.lan"

    machine.vm.provider :libvirt do |domain|
      domain.memory = 16384
      domain.cpus = 8
      domain.machine_virtual_size = 144
      domain.nested = true
      domain.cpu_model = 'host-model'
    end
    machine.vm.network :public_network, :ip => "172.16.20.10", :dev => "virbr2", :mode => "bridge", :type => "bridge", :network_name => "dev-lan"
  end

  config.vm.provision "shell", path: "../../scripts/mirror/setup-repos.sh"
  config.vm.provision "shell", path: "../../scripts/foreman/bootstrap.sh"
  config.vm.provision "shell", path: "../../scripts/tools/bootstrap.sh"

  config.vm.provision "shell" do |s|
    ssh_public_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_public_key} >> /home/vagrant/.ssh/authorized_keys
      mkdir -p /usr/share/foreman/.ssh
      chown -R foreman:foreman /usr/share/foreman/.ssh
      chmod -R go-rwx /usr/share/foreman/.ssh
    SHELL
  end

  config.vm.provision "shell", path: "../../scripts/foreman/postinstall.sh"

end
